# Generated by Django 5.2.8 on 2026-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
